# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_app', '0002_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fav_present',
            field=models.TextField(blank=True, default=None),
        ),
    ]
