# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_app', '0003_auto_20160806_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fav_present',
            field=models.TextField(blank=True, default=''),
        ),
    ]
