# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa_app', '0011_auto_20160806_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fav_color',
            field=models.TextField(blank=True, default='', verbose_name='Любимый цвет'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fav_film',
            field=models.TextField(blank=True, default='', verbose_name='Любимый фильм'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fav_game',
            field=models.TextField(blank=True, default='', verbose_name='Любимая игра'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hobbies',
            field=models.TextField(blank=True, default='', verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='key_words',
            field=models.TextField(blank=True, default='', verbose_name='Слова, которые помогут твоему Санте :)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fav_present',
            field=models.TextField(blank=True, default='', verbose_name='Лучший подарок, который тебе дарили'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='real_name',
            field=models.CharField(max_length=100, verbose_name='Имя, которое будет отображаться твоему Санте'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
